# DNS is deliberately NOT managed here.
#
# The hosted zone for this deployment's parent domain lives in a different AWS
# account from the one this stack is applied to, so Terraform has no way to
# write records into it. Rather than pretend otherwise -- a `data` lookup of a
# zone in another account simply fails -- this file computes every record that
# has to exist and exposes them as an output for whoever administers that zone
# to create by hand.
#
# The consequence to plan around: `aws_acm_certificate_validation` in acm.tf
# blocks until the certificate's validation record is live, so the first apply
# is a two-phase affair. See DEVELOPMENT.md.
#
# If the zone ever moves into this account, replace this file with ordinary
# `aws_route53_record` resources and a `data "aws_route53_zone"` lookup; the
# values below are already exactly what those records need to contain.

locals {
  # CloudFront's fixed, global hosted-zone id -- the same for every
  # distribution in every account. Only needed if the records below are
  # created as Route53 alias records rather than plain CNAMEs.
  cloudfront_alias_zone_id = "Z2FDTNDATAQYW2"

  dns_records_required = concat(
    [
      {
        name    = var.support_domain
        type    = "A / AAAA (alias) or CNAME"
        value   = aws_cloudfront_distribution.web.domain_name
        purpose = "Serves the web app. An alias record in Route53 (zone ${local.cloudfront_alias_zone_id}), or a plain CNAME in any other DNS provider."
      },
      {
        name    = var.support_domain
        type    = "MX"
        value   = "10 inbound-smtp.${var.aws_region}.amazonaws.com"
        purpose = "Delivers inbound mail to SES. Without this, nothing reaches the ticket system."
      },
      {
        name    = var.support_domain
        type    = "TXT"
        value   = "v=spf1 include:amazonses.com ~all"
        purpose = "SPF: authorises SES to send as this domain."
      },
      {
        name    = "_dmarc.${var.support_domain}"
        type    = "TXT"
        value   = var.alert_email == "" ? "v=DMARC1; p=none" : "v=DMARC1; p=none; rua=mailto:${var.alert_email}"
        purpose = "DMARC. p=none to start -- tighten once you have seen the reports."
      },
      {
        name    = aws_sesv2_email_identity_mail_from_attributes.main.mail_from_domain
        type    = "MX"
        value   = "10 feedback-smtp.${var.aws_region}.amazonses.com"
        purpose = "Custom MAIL FROM: bounce and complaint feedback."
      },
      {
        name    = aws_sesv2_email_identity_mail_from_attributes.main.mail_from_domain
        type    = "TXT"
        value   = "v=spf1 include:amazonses.com ~all"
        purpose = "SPF for the custom MAIL FROM subdomain."
      },
    ],
    # DKIM: three CNAMEs, generated by SES when the identity is created.
    [
      for token in aws_sesv2_email_identity.main.dkim_signing_attributes[0].tokens : {
        name    = "${token}._domainkey.${var.support_domain}"
        type    = "CNAME"
        value   = "${token}.dkim.amazonses.com"
        purpose = "DKIM signing. All three must exist before SES will sign outbound mail."
      }
    ],
    # ACM validation: the certificate cannot issue, and therefore CloudFront
    # cannot serve TLS, until this exists.
    [
      for opt in aws_acm_certificate.web.domain_validation_options : {
        name    = opt.resource_record_name
        type    = opt.resource_record_type
        value   = opt.resource_record_value
        purpose = "ACM certificate validation. The first apply BLOCKS on this -- create it, then re-apply."
      }
    ],
  )
}

output "dns_records_required" {
  description = "Every DNS record that must be created by hand in the parent zone (which lives in another account). Create the ACM validation record first: the initial apply blocks until the certificate issues."
  value       = local.dns_records_required
}
